### ISSUE TITLE
nokogiri and MAC

### ISSUE THREAD

**Issue by neuwirthe** [jonclayden/r-manuals#1]
2 days ago I found this project and built the manuals on OSX Mountain Lion. It went smoothly after installing Hpricot.
Today, I found that the build mechanism has been changed and installed nokigiri which seems to give errors.

Mercator:r-manuals neuwirth$ sudo gem install nokogiri
Password:
Building native extensions.  This could take a while...
Successfully installed nokogiri-1.5.5
1 gem installed
Installing ri documentation for nokogiri-1.5.5...

No definition for get_options

No definition for set_options

No definition for parse_memory

No definition for parse_file

No definition for parse_with
Installing RDoc documentation for nokogiri-1.5.5...

No definition for get_options

No definition for set_options

No definition for parse_memory

No definition for parse_file

No definition for parse_with

make for the r-manuals then does not work any more:

Mercator:r-manuals neuwirth$ make
Building R-admin.html... /Library/Ruby/Gems/1.8/gems/nokogiri-1.5.5/lib/nokogiri/nokogiri.bundle: dlopen(/Library/Ruby/Gems/1.8/gems/nokogiri-1.5.5/lib/nokogiri/nokogiri.bundle, 9): no suitable image found.  Did find: (LoadError)
    /Library/Ruby/Gems/1.8/gems/nokogiri-1.5.5/lib/nokogiri/nokogiri.bundle: mach-o, but wrong architecture - /Library/Ruby/Gems/1.8/gems/nokogiri-1.5.5/lib/nokogiri/nokogiri.bundle
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `require'
    from /Library/Ruby/Gems/1.8/gems/nokogiri-1.5.5/lib/nokogiri.rb:27
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:60:in`gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:60:in `require'
    from ./build.rb:4
make[1]: **\* [R-admin.html] Error 1
make: **\* [build] Error 1

Any hints?

**Comment by jonclayden** [comment]
It may be to do with ARCHFLAGS, if you're setting it in your .bashrc or otherwise. See for example http://stackoverflow.com/questions/5255995/ruby-debug-base-gem-gives-error-ruby-mach-o-wrong-architecture. FWIW I also run Mountain Lion and Nokogiri installed cleanly for me, albeit on Homebrew-installed Ruby 1.9.

The switch to Nokogiri was made to avoid a fairly minor bug in the HTML emitted by Hpricot, so if you can't get Nokogiri working you won't lose much by reverting to a commit before the switch.

**Comment by sandsfish** [comment]
Anyone find a resolution for this?  I tried uninstalling and reinstalling the gem with both the 64-bit ARCHFLAGS set, as well as i386 just to see.  Same result.  Still wondering...

**Comment by jonclayden** [comment]
Is this with the standard system ruby on Mountain Lion? Is your environment substantially modified in any other relevant way? Even using the current system ruby (v1.8.7p358) I can't reproduce the error.
